# Generated by Django 6.0 on 2025-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Card Mark Staff')], default='staff', max_length=20),
        ),
    ]
