# Generated by Django 6.0 on 2025-12-08 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['-is_primary', 'name'], 'verbose_name': 'Guardian', 'verbose_name_plural': 'Guardians'},
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=20),
        ),
    ]
