# Generated by Django 6.0 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_alter_guardian_options_guardian_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20),
        ),
    ]
